function c = defaults()
% Native MATLAB implementation; pixel coordinates are ONE-based [x y w h].
c = struct('video','','rois',[],'fps',[],'maxFrames',Inf,...
    'radius',32,'maxSamples',1600,'minNCC',0.55,'maxError',0.55,...
    'maxIterations',20,'referenceModel','translation','targetMode','profile','referenceTracker','anchor',...
    'output','','axis','x','profileScale',true,'affine',true,'guideMode','geometry','autoProfileRows',false,'fastSearch',false,'profileKeyframes',true,...
    'referenceSelection','manual','automaticReferenceCount',8,'automaticPatchSize',32,...
    'automaticMinReferences',3,'automaticMinInlierRatio',.6,'automaticConsensusTolerance',1.5,...
    'automaticMaxSpread',.75,'automaticAmbiguityRatio',.8,'automaticMinTextureStd',2,'automaticMinGradientEigenvalue',.05);
end
