function u=real_defaults()
% Public, compact real-video configuration. Laser is deliberately absent.
u=struct('videoPath','','outputRoot','','captureFPS',[],'maxFrames',Inf,...
    'roiMode','saved','roiSource','','targetROI',[],'referenceROIs',[],...
    'axis','x','targetMode','profile','referenceModel','translation',...
    'referenceSelection','manual','referenceTracker','anchor','searchROI',[],...
    'automaticReferenceCount',8,'automaticPatchSize',32,'automaticMinReferences',3,...
    'automaticMinInlierRatio',.6,'automaticConsensusTolerance',1.5,...
    'automaticMaxSpread',.75,'automaticAmbiguityRatio',.8,...
    'showFigures',true,'exportFigures',true,'analysisBandHz',[],...
    'denoise',false,'autoProfileRows',true,'maxSamples',6500);
end
