%% Batch processing: 0723 wind-tunnel videos (two source folders)
% Each entry is intentionally explicit so a user can comment/uncomment runs.
% The tracking/measurement path is the same public run_real_video method.
close all; clearvars; clc;
scriptRoot=fileparts(mfilename('fullpath')); projectRoot=fileparts(fileparts(scriptRoot));
addpath(fullfile(projectRoot,'src'));

videoFiles={ ...
    'D:\实验室\风洞项目\0723单目\1-0-1.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-0-2.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-0-3.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-30-1-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-30-1-t.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-30-2-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-32-1-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-32-1-t.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-32-1-w.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-32-2-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-33-1-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-33-1-t.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-33-1-w.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-33-2-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-33-2-t.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-33-2-w.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-33-3-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-33-3-t.mp4', ...
    'D:\实验室\风洞项目\0723单目\1-33-3-w.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-0-1.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-0-2.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-0-3.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-0-4.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-33-1-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-33-1-t.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-33-1-w.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-33-2-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-33-2-t.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-33-2-w.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-33-3-q.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-33-3-t.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\2-33-3-w.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\jiujiasudujiweizhi.mp4', ...
    'D:\实验室\风洞项目\0723单目\xinjiasuduji\shoujidoudong.mp4' ...
};

outputRoot=fullfile(projectRoot,'outputs','batch_0723_windtunnel');
for k=1:numel(videoFiles)
    videoPath=videoFiles{k};
    if ~isfile(videoPath), warning('Skipping missing video: %s',videoPath); continue; end
    [~,name]=fileparts(videoPath); fprintf('\n=== [%d/%d] %s ===\n',k,numel(videoFiles),name);
    u=mfm.real_defaults();
    u.videoPath=videoPath; u.outputRoot=outputRoot; u.captureFPS=[]; u.maxFrames=Inf; u.axis='x';
    u.roiMode='interactive'; u.targetROI=[]; u.roiSource='';
    u.referenceModel='translation'; u.referenceSelection='interactive'; u.referenceROIs=[];
    u.targetMode='direct'; u.referenceTracker='flow'; u.autoProfileRows=true; u.maxSamples=6500;
    u.analysisBandHz=[]; u.denoise=false; u.showFigures=true; u.exportFigures=true; u.exportTrackingVideo=false;
    result=run_real_video(u);
    outDir=fullfile(outputRoot,name);
    write_acceleration_outputs(result,outDir,name);
end
fprintf('\n0723 batch finished. Acceleration figures are under each video folder\\batch_acceleration.\n');

function write_acceleration_outputs(result,outDir,name)
% Acceleration is derived here from the measured displacement; core outputs are untouched.
if ~isfield(result,'relative') || isempty(result.relative), warning('No displacement for %s',name); return; end
axisId=1; if isfield(result,'cfg') && isfield(result.cfg,'axis') && strcmp(result.cfg.axis,'y'),axisId=2;end
x=double(result.relative(:,axisId)); fs=result.fps; valid=isfinite(x);
if nnz(valid)<4, warning('Too few valid samples for acceleration: %s',name); return; end
t=(0:numel(x)-1)'/fs; x=fillmissing(x,'linear','EndValues','nearest');
velocity=gradient(x,1/fs); acceleration=gradient(velocity,1/fs);
acceleration(~valid)=NaN;
if ~isfolder(fullfile(outDir,'batch_acceleration')), mkdir(fullfile(outDir,'batch_acceleration')); end
folder=fullfile(outDir,'batch_acceleration');
fig=figure('Visible','on','Color','w'); plot(t,acceleration,'LineWidth',1); grid on; xlabel('Time (s)'); ylabel('Acceleration (px/s^2)'); title([name ' acceleration'],'Interpreter','none'); savefig(fig,fullfile(folder,'acceleration_time.fig')); exportgraphics(fig,fullfile(folder,'acceleration_time.png')); close(fig);
[a,f]=one_sided_spectrum(acceleration,fs); ref=max(a); if ref>0,an=a/ref;else,an=zeros(size(a));end
fig=figure('Visible','on','Color','w'); plot(f,an,'LineWidth',1); grid on; xlabel('Frequency (Hz)'); ylabel('Normalized amplitude'); title([name ' normalized acceleration spectrum'],'Interpreter','none'); xlim([0 fs/2]); savefig(fig,fullfile(folder,'acceleration_spectrum_normalized.fig')); exportgraphics(fig,fullfile(folder,'acceleration_spectrum_normalized.png')); close(fig);
save(fullfile(folder,'acceleration.mat'),'t','x','velocity','acceleration','f','a','an','fs','valid','-v7');
end
function [a,f]=one_sided_spectrum(x,fs)
z=x(:);z(~isfinite(z))=0;z=z-mean(z);n=numel(z);nfft=2^nextpow2(max(n,2));w=hann(n);y=fft(z.*w,nfft);a=abs(y(1:nfft/2+1))/max(sum(w),eps)*2; a(1)=a(1)/2; f=(0:nfft/2)'*fs/nfft;
end
