%% Batch processing: 0819 videos from D:, C:, and E: drives
% Comment individual entries in videoFiles to control which videos run.
close all; clearvars; clc;
scriptRoot=fileparts(mfilename('fullpath')); projectRoot=fileparts(fileparts(scriptRoot)); addpath(fullfile(projectRoot,'src'));
videoFiles={ ...
    'D:\0819\3-25mvpp-motion.avi', ...
    'D:\0819\3-25mvpp-static.avi', ...
    'D:\0819\car.avi', ...
    'D:\0819\drone.avi', ...
    'C:\0819\2-25mvpp-luandong.avi', ...
    'C:\0819\2-5mvpp-motion.avi', ...
    'C:\0819\2-5mvpp-static.avi', ...
    'C:\0819\4-25mvpp-luandong.avi', ...
    'C:\0819\4-25mvpp-motion.avi', ...
    'C:\0819\4-25mvpp-static.avi', ...
    'C:\0819\sun-3050-30mvpp.mp4', ...
    'E:\0819\1-25mvpp-motion.avi', ...
    'E:\0819\1-25mvpp-static.avi' ...
};
outputRoot=fullfile(projectRoot,'outputs','batch_0819_all');
for k=1:numel(videoFiles)
    videoPath=videoFiles{k};
    if ~isfile(videoPath), warning('Skipping missing video: %s',videoPath); continue; end
    [~,name]=fileparts(videoPath); fprintf('\n=== [%d/%d] %s ===\n',k,numel(videoFiles),name);
    u=mfm.real_defaults(); u.videoPath=videoPath; u.outputRoot=outputRoot;
    u.captureFPS=[]; u.maxFrames=Inf; u.axis='x';
    u.roiMode='interactive'; u.targetROI=[]; u.roiSource='';
    u.referenceModel='translation'; u.referenceSelection='interactive'; u.referenceROIs=[];
    u.targetMode='direct'; u.referenceTracker='flow'; u.autoProfileRows=true; u.maxSamples=6500;
    u.analysisBandHz=[]; u.denoise=false; u.showFigures=true; u.exportFigures=true; u.exportTrackingVideo=false;
    run_real_video(u);
end
fprintf('\n0819 batch finished.\n');
